/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://zspgcdjfabfm3oinqypiidjnzy.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kwmekluv2vdyti4zp5zmqklfuq",
    "aws_cognito_identity_pool_id": "us-west-1:ee6a5f3f-98d5-4bcc-b788-95ad02de5e11",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_65jCzh3Cv",
    "aws_user_pools_web_client_id": "3m77tjonm3ejhvq7depvne8dec",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
